ss (#10)
* ss

* updated

* updated

* r

* f

* rs

* erl

* test

* ram

* r

* test

* push

* rt

* final test

* a

* corrected

* rm

* finaly completed

* rlkd

* read

diff --git a/.github/workflows/android-lint.yml b/.github/workflows/android-lint.yml
--- a/.github/workflows/android-lint.yml
+++ b/.github/workflows/android-lint.yml
@@ -14,6 +14,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+        with:
+          clean: true
 
       - name: Set up JDK
         uses: actions/setup-java@v3
@@ -21,8 +23,23 @@ jobs:
           java-version: '11'
           distribution: 'zulu'
 
-      - name: Build with Gradle
-        run: ./gradlew build
+      - name: Set execute permissions
+        run: chmod +x gradlew
 
       - name: Run lint
-        run: ./gradlew lint
+        run: bash ./gradlew lintDebug
+
+      - name: check lint issues
+        run: |
+          if grep -q "Lint found errors" app/build/reports/lint-results-debug.html; then
+            echo "Lint issues found, failing the workflow."
+            exit 1
+          else
+            echo "No Lint issues found."
+          fi
+
+      - name: Upload html test report
+        uses: actions/upload-artifact@v2
+        with:
+          name: index.html
+          path: app/build/reports/lint-results-debug.html
